config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  resources :posts, only: [:index, :new, :create, :show]
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { minimum: 3 }
  validates :body, presence: true, length: { minimum: 3 }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show]
  before_action :authenticate_user!, only: %i[new create]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show; end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/commons/_header.html.erb
<nav class="navbar py-2 d-flex justify-content-between">
  <div class="container">
    <div class="navbar-start">
      <div class="title">
        <%= link_to  "MEMBERS-ONLY", root_path, class: 'title-link' %>
        <span></span>
      </div> 
    </div>
  
    <div class="navbar-end d-flex">
      <%- if user_signed_in? %>
      <div class="nav-item d-flex align-items-center mr-5">
        <%= link_to  "SIGN OUT", destroy_user_session_path, :method => :delete, class: 'link-items' %>
      </div>
      <div class="nav-item">
        <div class="profile-pic d-flex justify-content-center align-items-center"><span><%= current_user.name.upcase[0, 2] %></span></div>
      </div>
      <% else %>
      <div class="nav-item d-flex justify-content-center align-items-center">
          <%= link_to "Log in", new_user_session_path, class: "link-items" %>
      </div>
      <div class="nav-item d-flex justify-content-center align-items-center">
          <%= link_to "Sign up", new_user_registration_path, class: "link-items" %>
      </div>
      <% end %>
    </div>
 </div> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnlyProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%- if notice %>
      <div class="alert alert-success p-3 m-0" role="alert">
        <div class="container"><%= notice %></div>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="form-content">

<%= form_with(model: post, local: true) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation" class="error-message">
      <h3><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h3>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="post-field">
    <%= f.label :title %><br />
    <%= f.text_field :title, autofocus: true %>
  </div>

  <div class="post-field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>

  <div class="actions mt-4">
    <%= f.submit %>
  </div>
<% end %>


</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= render "commons/header" %>
<div class="container post-index">
  <%- if user_signed_in?%>
    <div class="d-flex align-items-end flex-row mt-3">
      <div class="p-2">
        <%= link_to 'New Post', new_post_path, class: 'new-post pb-2' %>
      </div>
    </div>
  <% end %>

  <div class="row post-list p-3">
  <% @posts.each do |post| %>
    <article class="col-xl-4 my-3">
     <div class="post-item p-3">
       <h2 class="title"><%= link_to  post.title, post_path(post), class: 'title-link' %></h2>
        <p class="body"><%= post.body %></p>
        <%- if user_signed_in?%>
          <div class="profile mt-5 d-flex">
          <div class="profile-pic d-flex justify-content-center align-items-center"><span><%= post.user.name.upcase[0, 2] %></span></div>
            <div class="profile-info d-flex flex-column">
              <span><%= post.user.name %></span> 
              <small><%= post.user.email %></small> 
            </div>
          </div>
        <% end %>
     </div>
   </article>
  <% end %> 
  </div>
  
</div>

app/views/posts/new.html.erb
<%= render "commons/header" %>
<div class="container mt-5">
 <h1>New Post</h1>

  <div class="mt-5">
    <%= render 'form', post: @post %>
  </div>

  <%= link_to '← Back', posts_path %>
</div>

app/views/posts/show.html.erb
<%= render "commons/header" %>

<div class="container show-post-content pb-5">

  <%- if user_signed_in?%>
    <div class="profile mt-5 d-flex">
      <div class="profile-pic d-flex justify-content-center align-items-center"><span><%= @post.user.name.upcase[0, 2] %></span></div>
        <div class="profile-info d-flex flex-column">
          <span><%= @post.user.name %></span> 
          <small><%= @post.user.email %></small> 
        </div>
     </div>
  <% end %>

  <div class="post-info mt-5">
    <div class="title">
      <h3><%= @post.title%></h3>
    </div>
    <div class="body">
      <p><%= @post.body%></p>
    </div>
  </div>

  <%= link_to '← Back', posts_path %>
</div>